# Generated by Django 5.0.6 on 2024-06-02 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id_os', models.AutoField(primary_key=True, serialize=False)),
                ('nom_de_os', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plateforme',
            fields=[
                ('id_plateforme', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MEP',
            fields=[
                ('id_mep', models.AutoField(primary_key=True, serialize=False)),
                ('responsable', models.CharField(max_length=100)),
                ('nom_plateforme', models.CharField(max_length=100)),
                ('version_os', models.CharField(max_length=50)),
                ('vm_ajout', models.CharField(max_length=100)),
                ('version_sgbd', models.CharField(max_length=50)),
                ('version_applicatif', models.CharField(max_length=50)),
                ('nom_dns', models.CharField(max_length=100)),
                ('host_production', models.CharField(max_length=100)),
                ('date_production', models.DateField()),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.os')),
                ('plateforme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plateforme')),
            ],
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id_backup', models.AutoField(primary_key=True, serialize=False)),
                ('nom_du_serveur', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=100)),
                ('adresse_ip', models.CharField(max_length=15)),
                ('nom_dns', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=100)),
                ('type_de_os', models.CharField(max_length=50)),
                ('applicatif', models.CharField(max_length=100)),
                ('responsable_svc', models.CharField(max_length=100)),
                ('backup_svc', models.CharField(max_length=100)),
                ('provenance', models.CharField(max_length=100)),
                ('chemin_fichier', models.CharField(max_length=255)),
                ('taille_du_fichier', models.CharField(max_length=100)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.os')),
                ('plateforme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plateforme')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Director', 'Director'), ('Client', 'Client')], max_length=20)),
                ('platform', models.ManyToManyField(to='main.plateforme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vcenter',
            fields=[
                ('id_vcenter', models.AutoField(primary_key=True, serialize=False)),
                ('nom_vcenter', models.CharField(max_length=100)),
                ('adresse_ip', models.CharField(max_length=15)),
                ('plateforme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plateforme')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id_directeur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_directeur', models.CharField(max_length=100)),
                ('mot_de_passe', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('plateforme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plateforme')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.role')),
                ('vcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vcenter')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom_client', models.CharField(max_length=100)),
                ('mot_de_passe', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('plateforme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.plateforme')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.role')),
                ('vcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vcenter')),
            ],
        ),
        migrations.CreateModel(
            name='VM',
            fields=[
                ('id_vm', models.AutoField(primary_key=True, serialize=False)),
                ('nom_de_la_vm', models.CharField(max_length=100)),
                ('departement', models.CharField(max_length=100)),
                ('type_de_vm', models.CharField(max_length=100)),
                ('nombre_de_cpu', models.IntegerField()),
                ('ram', models.IntegerField()),
                ('actif', models.BooleanField(default=False)),
                ('disque', models.IntegerField()),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.os')),
                ('vcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vcenter')),
            ],
        ),
    ]
