# Generated by Django 5.0.6 on 2024-06-02 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='plateforme',
        ),
        migrations.RemoveField(
            model_name='director',
            name='role',
        ),
        migrations.RemoveField(
            model_name='director',
            name='vcenter',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
    ]
